spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tdata
    username: root
    password: root
  devtools:
    restart:
      enabled: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  cloud:
        consul:
            enabled: true
            host: 127.0.0.1
            port: 8500
  application:
    name: consul-service
    
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081  