server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tdata
    username: root
    password: root
    
  devtools:
    restart:
      enabled: true
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
  application:
    name: service2   
          